# Generated by Django 3.0.6 on 2020-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fontsapp', '0002_auto_20200525_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
