# Generated by Django 3.0.6 on 2020-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fontsapp', '0005_auto_20200706_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='output_photo1',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
    ]
