# Generated by Django 3.0.6 on 2020-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fontsapp', '0007_auto_20200720_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='no_checkpoint',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
