# Generated by Django 3.0.6 on 2020-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fontsapp', '0010_remove_font_phrase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='final_phrase',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
