# Generated by Django 3.0.6 on 2020-08-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fontsapp', '0012_font_create_later'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='create_later',
            new_name='createlater',
        ),
    ]
